/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedGruposRouteImport } from './routes/_authenticated/grupos'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedOfertasRouteImport } from './routes/_authenticated/ofertas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedShopeeAnalyticsRouteImport } from './routes/_authenticated/shopee-analytics'
import { Route as AuthenticatedWhatsappIndexRouteImport } from './routes/_authenticated/whatsapp/index'
import { Route as AuthenticatedWhatsappConexoesRouteImport } from './routes/_authenticated/whatsapp/conexoes'
import { Route as AuthenticatedWhatsappConfiguracoesRouteImport } from './routes/_authenticated/whatsapp/configuracoes'
import { Route as AuthenticatedWhatsappGruposRouteImport } from './routes/_authenticated/whatsapp/grupos'
import { Route as AuthenticatedWhatsappLogsRouteImport } from './routes/_authenticated/whatsapp/logs'
import { Route as AuthenticatedWhatsappPublicacoesRouteImport } from './routes/_authenticated/whatsapp/publicacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGruposRoute = AuthenticatedGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfertasRoute = AuthenticatedOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopeeAnalyticsRoute =
  AuthenticatedShopeeAnalyticsRouteImport.update({
    id: '/shopee-analytics',
    path: '/shopee-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappIndexRoute =
  AuthenticatedWhatsappIndexRouteImport.update({
    id: '/whatsapp/',
    path: '/whatsapp/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappConexoesRoute =
  AuthenticatedWhatsappConexoesRouteImport.update({
    id: '/whatsapp/conexoes',
    path: '/whatsapp/conexoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappConfiguracoesRoute =
  AuthenticatedWhatsappConfiguracoesRouteImport.update({
    id: '/whatsapp/configuracoes',
    path: '/whatsapp/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappGruposRoute =
  AuthenticatedWhatsappGruposRouteImport.update({
    id: '/whatsapp/grupos',
    path: '/whatsapp/grupos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappLogsRoute =
  AuthenticatedWhatsappLogsRouteImport.update({
    id: '/whatsapp/logs',
    path: '/whatsapp/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappPublicacoesRoute =
  AuthenticatedWhatsappPublicacoesRouteImport.update({
    id: '/whatsapp/publicacoes',
    path: '/whatsapp/publicacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/shopee-analytics': typeof AuthenticatedShopeeAnalyticsRoute
  '/whatsapp/conexoes': typeof AuthenticatedWhatsappConexoesRoute
  '/whatsapp/configuracoes': typeof AuthenticatedWhatsappConfiguracoesRoute
  '/whatsapp/grupos': typeof AuthenticatedWhatsappGruposRoute
  '/whatsapp/logs': typeof AuthenticatedWhatsappLogsRoute
  '/whatsapp/publicacoes': typeof AuthenticatedWhatsappPublicacoesRoute
  '/whatsapp/': typeof AuthenticatedWhatsappIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/shopee-analytics': typeof AuthenticatedShopeeAnalyticsRoute
  '/whatsapp/conexoes': typeof AuthenticatedWhatsappConexoesRoute
  '/whatsapp/configuracoes': typeof AuthenticatedWhatsappConfiguracoesRoute
  '/whatsapp/grupos': typeof AuthenticatedWhatsappGruposRoute
  '/whatsapp/logs': typeof AuthenticatedWhatsappLogsRoute
  '/whatsapp/publicacoes': typeof AuthenticatedWhatsappPublicacoesRoute
  '/whatsapp': typeof AuthenticatedWhatsappIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/grupos': typeof AuthenticatedGruposRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/ofertas': typeof AuthenticatedOfertasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/shopee-analytics': typeof AuthenticatedShopeeAnalyticsRoute
  '/_authenticated/whatsapp/conexoes': typeof AuthenticatedWhatsappConexoesRoute
  '/_authenticated/whatsapp/configuracoes': typeof AuthenticatedWhatsappConfiguracoesRoute
  '/_authenticated/whatsapp/grupos': typeof AuthenticatedWhatsappGruposRoute
  '/_authenticated/whatsapp/logs': typeof AuthenticatedWhatsappLogsRoute
  '/_authenticated/whatsapp/publicacoes': typeof AuthenticatedWhatsappPublicacoesRoute
  '/_authenticated/whatsapp/': typeof AuthenticatedWhatsappIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/fila'
    | '/grupos'
    | '/integracoes'
    | '/ofertas'
    | '/relatorios'
    | '/shopee-analytics'
    | '/whatsapp/conexoes'
    | '/whatsapp/configuracoes'
    | '/whatsapp/grupos'
    | '/whatsapp/logs'
    | '/whatsapp/publicacoes'
    | '/whatsapp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/fila'
    | '/grupos'
    | '/integracoes'
    | '/ofertas'
    | '/relatorios'
    | '/shopee-analytics'
    | '/whatsapp/conexoes'
    | '/whatsapp/configuracoes'
    | '/whatsapp/grupos'
    | '/whatsapp/logs'
    | '/whatsapp/publicacoes'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/automacoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/fila'
    | '/_authenticated/grupos'
    | '/_authenticated/integracoes'
    | '/_authenticated/ofertas'
    | '/_authenticated/relatorios'
    | '/_authenticated/shopee-analytics'
    | '/_authenticated/whatsapp/conexoes'
    | '/_authenticated/whatsapp/configuracoes'
    | '/_authenticated/whatsapp/grupos'
    | '/_authenticated/whatsapp/logs'
    | '/_authenticated/whatsapp/publicacoes'
    | '/_authenticated/whatsapp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grupos': {
      id: '/_authenticated/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ofertas': {
      id: '/_authenticated/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof AuthenticatedOfertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shopee-analytics': {
      id: '/_authenticated/shopee-analytics'
      path: '/shopee-analytics'
      fullPath: '/shopee-analytics'
      preLoaderRoute: typeof AuthenticatedShopeeAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/': {
      id: '/_authenticated/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof AuthenticatedWhatsappIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/conexoes': {
      id: '/_authenticated/whatsapp/conexoes'
      path: '/whatsapp/conexoes'
      fullPath: '/whatsapp/conexoes'
      preLoaderRoute: typeof AuthenticatedWhatsappConexoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/configuracoes': {
      id: '/_authenticated/whatsapp/configuracoes'
      path: '/whatsapp/configuracoes'
      fullPath: '/whatsapp/configuracoes'
      preLoaderRoute: typeof AuthenticatedWhatsappConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/grupos': {
      id: '/_authenticated/whatsapp/grupos'
      path: '/whatsapp/grupos'
      fullPath: '/whatsapp/grupos'
      preLoaderRoute: typeof AuthenticatedWhatsappGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/logs': {
      id: '/_authenticated/whatsapp/logs'
      path: '/whatsapp/logs'
      fullPath: '/whatsapp/logs'
      preLoaderRoute: typeof AuthenticatedWhatsappLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/publicacoes': {
      id: '/_authenticated/whatsapp/publicacoes'
      path: '/whatsapp/publicacoes'
      fullPath: '/whatsapp/publicacoes'
      preLoaderRoute: typeof AuthenticatedWhatsappPublicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedGruposRoute: typeof AuthenticatedGruposRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedOfertasRoute: typeof AuthenticatedOfertasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedShopeeAnalyticsRoute: typeof AuthenticatedShopeeAnalyticsRoute
  AuthenticatedWhatsappConexoesRoute: typeof AuthenticatedWhatsappConexoesRoute
  AuthenticatedWhatsappConfiguracoesRoute: typeof AuthenticatedWhatsappConfiguracoesRoute
  AuthenticatedWhatsappGruposRoute: typeof AuthenticatedWhatsappGruposRoute
  AuthenticatedWhatsappLogsRoute: typeof AuthenticatedWhatsappLogsRoute
  AuthenticatedWhatsappPublicacoesRoute: typeof AuthenticatedWhatsappPublicacoesRoute
  AuthenticatedWhatsappIndexRoute: typeof AuthenticatedWhatsappIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedGruposRoute: AuthenticatedGruposRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedOfertasRoute: AuthenticatedOfertasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedShopeeAnalyticsRoute: AuthenticatedShopeeAnalyticsRoute,
  AuthenticatedWhatsappConexoesRoute: AuthenticatedWhatsappConexoesRoute,
  AuthenticatedWhatsappConfiguracoesRoute:
    AuthenticatedWhatsappConfiguracoesRoute,
  AuthenticatedWhatsappGruposRoute: AuthenticatedWhatsappGruposRoute,
  AuthenticatedWhatsappLogsRoute: AuthenticatedWhatsappLogsRoute,
  AuthenticatedWhatsappPublicacoesRoute: AuthenticatedWhatsappPublicacoesRoute,
  AuthenticatedWhatsappIndexRoute: AuthenticatedWhatsappIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
